export const playerAutoGeneratedScript = `
    <iframe height="75" width="100%" src="https://playerssl.radioonlinehd.com/ads/radioanimex/BASICO/" scrolling="no" style="border: none"></iframe>
    <script type="text/javascript" src="https://hosted.muses.org/mrp.js"></script>
    <script type="text/javascript">
        MRP.insert({
        'url':'http://stream.zeno.fm/b3tz3g94vv8uv',
        'codec':'mp3',
        'volume':0,
        'autoplay':true,
        'jsevents':true,
        'buffering':0,
        'title':'Anime',
        'wmode':'transparent',
        'skin':'repvku-115',
        'width':0,
        'height':0
        })
    </script>
`

export const chatAutoGeneratedScript = `
    <div id="chat-box" class="spoiler">
    <script id="cid0020000249709655376" data-cfasync="false" async src="//st.chatango.com/js/gz/emb.js" style="width: 800px;height: 600px;">{"handle":"radioanimex-net","arch":"js","styles":{"a":"ff6c38","b":100,"c":"ffffff","d":"ff6c38","g":"000099","j":"ff6c38","k":"ffffff","l":"ff6c38","m":"ff6c38","p":"10","q":"ff6c38","r":100,"usricon":0,"cnrs":"0.71","fwtickm":1}}</script>
`