export const autoGeneratedScript = `
    <iframe height="75" width="100%" src="https://playerssl.radioonlinehd.com/ads/radioanimex/BASICO/" scrolling="no" style="border: none"></iframe>
    <script type="text/javascript" src="https://hosted.muses.org/mrp.js"></script>
    <script type="text/javascript">
        MRP.insert({
        'url':'http://stream.zeno.fm/b3tz3g94vv8uv',
        'codec':'mp3',
        'volume':0,
        'autoplay':true,
        'jsevents':true,
        'buffering':0,
        'title':'Anime',
        'wmode':'transparent',
        'skin':'repvku-115',
        'width':0,
        'height':0
        })
    </script>
`