import { autoGeneratedScript } from "./constants"
import { RadioAnimexBackground, RadioAnimexContent, RadioAnimexContentImage, RadioAnimexWrapper, RadioAnimexContentInfo, RadioAnimexContentInfoTitle, RadioAnimexContentInfoPlayer } from "./styled"
import { Button } from "../../components/Button"

export const RadioAnimexStickyWindow: React.FC = () => {
    return(
        <>
        {/* <iframe height="75" width="100%" src="https://playerssl.radioonlinehd.com/ads/radioanimex/BASICO/" scrolling="no" style={{border: 'none'}}></iframe>
        <div id="chat-box" class="spoiler" style="display: none;">
        <script id="cid0020000249709655376" data-cfasync="false" async src="//st.chatango.com/js/gz/emb.js" style="width: 100%;height: 400px;">{"handle":"radioanimex-net","arch":"js","styles":{"a":"ff6c38","b":100,"c":"ff6c38","d":"ff6c38","g":"000099","j":"ff6c38","k":"ffffff","l":"ff6c38","m":"ff6c38","p":"10","q":"ff6c38","r":100,"usricon":0,"cnrs":"0.71","fwtickm":1}}</script>
        <div dangerouslySetInnerHTML={{__html: autoGeneratedScript}} /> */}

        <RadioAnimexWrapper>
            <RadioAnimexBackground />
            <RadioAnimexContent>
                <RadioAnimexContentImage src="/images/radio-animex-logo.jpg" />
                <RadioAnimexContentInfo>
                    <RadioAnimexContentInfoTitle>
                        <span>Ahora: </span><h3>Programa Radio Animex - Live</h3><span className="blink-2">⬤</span>
                    </RadioAnimexContentInfoTitle>
                    <RadioAnimexContentInfoPlayer>
                        <div dangerouslySetInnerHTML={{__html: autoGeneratedScript}} />
                    </RadioAnimexContentInfoPlayer>
                </RadioAnimexContentInfo>
            </RadioAnimexContent>
        </RadioAnimexWrapper>
    </>
    )
}