import { playerAutoGeneratedScript, chatAutoGeneratedScript } from "./constants"
import { RadioAnimexBackground, RadioAnimexContent, RadioAnimexContentImage, RadioAnimexWrapper, RadioAnimexContentInfoTitle, RadioAnimexContentInfoPlayer, Chatbox, TitleChatbox } from "./styled"
import { Button } from "../../components/Button"
import { Modal } from "../../components/Modal"
import { useState } from "react"

export const RadioAnimexStickyWindow: React.FC = () => {

    const [showModal, setShowModal] = useState(false)

    const handleCloseModal = () => setShowModal(false)
    const handleOpenModal = () => setShowModal(true)

    return(
        <>
        {/* <iframe height="75" width="100%" src="https://playerssl.radioonlinehd.com/ads/radioanimex/BASICO/" scrolling="no" style={{border: 'none'}}></iframe>
        <div id="chat-box" class="spoiler">
        <script id="cid0020000249709655376" data-cfasync="false" async src="//st.chatango.com/js/gz/emb.js">{"handle":"radioanimex-net","arch":"js","styles":{"a":"ff6c38","b":100,"c":"ff6c38","d":"ff6c38","g":"000099","j":"ff6c38","k":"ffffff","l":"ff6c38","m":"ff6c38","p":"10","q":"ff6c38","r":100,"usricon":0,"cnrs":"0.71","fwtickm":1}}</script>
        <div dangerouslySetInnerHTML={{__html: autoGeneratedScript}} /> */}
        <Modal show={showModal} onClose={handleCloseModal}>
            <TitleChatbox>Chat Radio Animex</TitleChatbox>
            <Chatbox dangerouslySetInnerHTML={{__html: chatAutoGeneratedScript}} />
        </Modal>
        <RadioAnimexWrapper>
            <RadioAnimexBackground />
            <RadioAnimexContent>
                <RadioAnimexContentInfoTitle>
                    <RadioAnimexContentImage src="/images/radio-animex-logo.jpg" />
                    <span>Ahora: </span><h3>Programa Radio Animex - Live</h3><span className="blink-2">⬤</span>
                </RadioAnimexContentInfoTitle>
                <RadioAnimexContentInfoPlayer>
                    <div dangerouslySetInnerHTML={{__html: playerAutoGeneratedScript}} />
                </RadioAnimexContentInfoPlayer>
                <Button onClick={handleOpenModal}>Pedir Canción</Button>
            </RadioAnimexContent>
        </RadioAnimexWrapper>
    </>
    )
}